on:
  workflow_dispatch:
name: ğŸš€ Deploy website on Click
jobs:
  web-deploy:
    name: ğŸ‰ Deploy website on Click
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v5
      - name: ğŸ“¦ Install dependencies
        run: npm install
      - name: ğŸ› ï¸ Build project
        run: npm run build
      # - name: ğŸ“„ Copy .htaccess to dist folder
      #   run: cp .htaccess dist/
      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 15.204.197.218
          username: ${{ secrets.TEST_FTP_USERNAME }}
          password: ${{ secrets.TEST_FTP_PASSWORD }}
          protocol: ftp
          server-dir: /
          local-dir: dist/
